// tslint:disable
/**
 * stock-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    nom?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    prenom?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    realm?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof Account
     */
    emailVerified?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof Account
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Account
     */
    updatedAt?: Date;
}

export function AccountFromJSON(json: any): Account {
    return {
        'nom': !exists(json, 'nom') ? undefined : json['nom'],
        'prenom': !exists(json, 'prenom') ? undefined : json['prenom'],
        'realm': !exists(json, 'realm') ? undefined : json['realm'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'email': json['email'],
        'emailVerified': !exists(json, 'emailVerified') ? undefined : json['emailVerified'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
    };
}

export function AccountToJSON(value?: Account): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'nom': value.nom,
        'prenom': value.prenom,
        'realm': value.realm,
        'username': value.username,
        'email': value.email,
        'emailVerified': value.emailVerified,
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
        'updatedAt': value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    };
}


