// tslint:disable
/**
 * stock-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountToken
 */
export interface AccountToken {
    /**
     * 
     * @type {string}
     * @memberof AccountToken
     */
    id: string;
    /**
     * time to live in seconds (2 weeks by default)
     * @type {number}
     * @memberof AccountToken
     */
    ttl?: number;
    /**
     * Array of scopes granted to this access token.
     * @type {Array<string>}
     * @memberof AccountToken
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof AccountToken
     */
    created?: Date;
    /**
     * 
     * @type {number}
     * @memberof AccountToken
     */
    userId?: number;
}

export function AccountTokenFromJSON(json: any): AccountToken {
    return {
        'id': json['id'],
        'ttl': !exists(json, 'ttl') ? undefined : json['ttl'],
        'scopes': !exists(json, 'scopes') ? undefined : json['scopes'],
        'created': !exists(json, 'created') ? undefined : new Date(json['created']),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function AccountTokenToJSON(value?: AccountToken): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'ttl': value.ttl,
        'scopes': value.scopes,
        'created': value.created === undefined ? undefined : value.created.toISOString(),
        'userId': value.userId,
    };
}


