// tslint:disable
/**
 * stock-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2001
     */
    _exists?: boolean;
}

export function InlineResponse2001FromJSON(json: any): InlineResponse2001 {
    return {
        '_exists': !exists(json, 'exists') ? undefined : json['exists'],
    };
}

export function InlineResponse2001ToJSON(value?: InlineResponse2001): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'exists': value._exists,
    };
}


