// tslint:disable
/**
 * stock-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information related to the outcome of the operation
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * The number of instances updated
     * @type {number}
     * @memberof InlineResponse2002
     */
    count?: number;
}

export function InlineResponse2002FromJSON(json: any): InlineResponse2002 {
    return {
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function InlineResponse2002ToJSON(value?: InlineResponse2002): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'count': value.count,
    };
}


