// tslint:disable
/**
 * stock-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Map principals to roles
 * @export
 * @interface RoleMapping
 */
export interface RoleMapping {
    /**
     * 
     * @type {number}
     * @memberof RoleMapping
     */
    id?: number;
    /**
     * The principal type, such as USER, APPLICATION, ROLE, or user model name in case of multiple user models
     * @type {string}
     * @memberof RoleMapping
     */
    principalType?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleMapping
     */
    principalId?: string;
    /**
     * 
     * @type {number}
     * @memberof RoleMapping
     */
    roleId?: number;
}

export function RoleMappingFromJSON(json: any): RoleMapping {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'principalType': !exists(json, 'principalType') ? undefined : json['principalType'],
        'principalId': !exists(json, 'principalId') ? undefined : json['principalId'],
        'roleId': !exists(json, 'roleId') ? undefined : json['roleId'],
    };
}

export function RoleMappingToJSON(value?: RoleMapping): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'principalType': value.principalType,
        'principalId': value.principalId,
        'roleId': value.roleId,
    };
}


